package voogasalad_GucciGames.gameEngine.gameConditions;

import junit.framework.TestCase;

/**
 * The class <code>ConditionParamsTest</code> contains tests for the class
 * {@link <code>ConditionParams</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 11/18/15 4:37 PM
 *
 * @author Sally Al
 *
 * @version $Revision$
 */
public class ConditionParamsTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public ConditionParamsTest(String name) {
		super(name);
	}

	public void removePlayerTest(){

	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames =
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods =
 * package = voogasalad_GucciGames.gameEngine.gameConditions
 * package.sourceFolder = voogasalad_GucciGames/src
 * superclassType = junit.framework.TestCase
 * testCase = ConditionParamsTest
 * testClassType = ConditionParams
 */