package voogasalad.util.cloud.tests;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.ResourceBundle;

import junit.framework.TestCase;
import voogasalad.util.cloud.data.CloudParameter;
import voogasalad.util.cloud.server.BasicPHPServer;
import voogasalad.util.cloud.server.CloudServer;

/**
 * The class <code>BasicPHPServerTest</code> contains tests for the class
 * {@link <code>BasicPHPServer</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 11/18/15 9:50 PM
 *
 * @author Ted Yavuzkurt
 *
 * @version $Revision$
 */
public class BasicPHPServerTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public BasicPHPServerTest(String name) {
		super(name);
	}

	/**
	 * Launch the test.
	 *
	 * @param args String[]
	 */
	public static void main(String[] args) {
		// add code to run tests here
	}

	private List<CloudParameter> myParams;
	private CloudServer myServer;
	
	/**
	 * Perform pre-test initialization
	 *
	 * @throws Exception
	 *
	 * @see TestCase#setUp()
	 */
	protected void setUp() throws Exception {
		super.setUp();
		// Add additional set up code here
		myParams = new ArrayList<>();
		myParams.add(new CloudParameter("action", "upload"));
		myParams.add(new CloudParameter("name", "Pwnage BBQ"));
		myParams.add(new CloudParameter("type", "gamedata"));
		myParams.add(new CloudParameter("player", ""));
		myServer = new BasicPHPServer();
	}
	
	public void testInitialize(){
		myServer.initializeID();
	}
	
	public void testEncoding(){
		String result = myServer.getRequestString(myParams);
		assertEquals("http://www.evokeone.com/voogasalad/dispatcher.php?action=upload&name=Pwnage+BBQ&type=gamedata", result);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = true
 * createSetUp = true
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = voogasalad.util.cloud
 * package.sourceFolder = voogasalad_util/src
 * superclassType = junit.framework.TestCase
 * testCase = BasicPHPServerTest
 * testClassType = voogasalad.util.cloud.server.BasicPHPServer
 */